version: '3.9'

services:
  chat-app-nestjs-prod:
    build:
      context: .
      target: prod
    container_name: chat-app-nestjs-prod-cont
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    command: npm run start:prod
    volumes:
      - .:/app # Mount source code for hot reload
      - /app/node_modules # Prevent overwriting node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-chat-db
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chat-app-nestjs
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  db_data:
